= SBuild Eclipse Plugin

http://sbuild.org/eclipse


== Installation

http://sbuild.org/eclipse

== Building SBuild Eclipse Plugin

To build, you need a recent SBuild installed.

----
git clone https://github.com/SBuild-org/sbuild-eclipse-plugin.git
cd sbuild-eclipse-plugin/update-site
sbuild update-site
----

After that, you will find an update-site under `update-site/target/update-site`.

== Changelog

=== SBuild Eclipse Plugin 0.5.0 - _not released yet_

* Extracted SBuild Resolver into separate Plugin, so that different SBuild resolvers can be used simultaneosly. For now, there are two resolver, one for the next upcomming SBuild version 0.8 (based on Scala 2.11) and one for older SBuild up until version 0.7.x (based on Scala 2.10).
* Support for SBuild 0.8.x
* Migrated to Scala 2.11
* Added new SBuild Nature plus a menu to simply be added the SBuild nature to any project.

=== SBuild Eclipse Plugin 0.1.0 - 0.4.3

* link:de.tototec.sbuild.eclipse.plugin/ChangeLog.txt[Changelog for SBuild Eclipse Plugin 0.1.0 - 0.4.x]
